name: Node.js CI/CD

on:
  push:
    branches:
      - main  # ajuste conforme sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get directory
      run: ls
      
    - name: Install dependencies
      run: npm install --prefix /home/runner/work/apartamentos/Backend

    - name: Start Application
      run: node /home/runner/work/apartamentos/Backend/server.js
