name: Debug Pipeline

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Navigate to backend directory
      run: cd Backend

    - name: Print current directory after cd
      run: |
        pwd
        ls -al
