name: Node.js CI/CD

on:
  push:
    branches:
      - main  # ajuste conforme sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Navigate to backend directory
      run: cd Backend

    - name: Install dependencies
      run: npm install

    - name: Start Application
      run: node server.js
